version: '3.8'

include:
  - path: src/Transactions/docker-compose.yml
  - path: src/Consolidated/docker-compose.yml

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: fluxocaixa-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: fluxocaixa-jaeger
    ports:
      - "16686:16686" # Jaeger Web UI (http://localhost:16686)
      - "4317:4317"   # OTLP gRPC Receiver
      - "4318:4318"   # OTLP HTTP Receiver
    environment:
      - COLLECTOR_OTLP_ENABLED=true
