include:
  - path: src/Transactions/docker-compose.yml
  - path: src/Consolidated/docker-compose.yml

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: fluxocaixa-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: fluxocaixa-jaeger
    ports:
      - "16686:16686" # Jaeger Web UI
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - SPAN_STORAGE_TYPE=memory

  loki:
    image: grafana/loki:3.0.0
    container_name: fluxocaixa-loki
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    volumes:
      - ./docker/observability/loki/loki.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki
    ports:
      - "3100:3100"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.98.0
    container_name: fluxocaixa-otel-collector
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./docker/observability/collector/otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - "4317:4317" # OTLP gRPC Receiver
      - "4318:4318" # OTLP HTTP Receiver
      - "8889:8889" # Prometheus Exporter
    depends_on:
      - jaeger
      - loki

  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: fluxocaixa-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    volumes:
      - ./docker/observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - otel-collector

  grafana:
    image: grafana/grafana:latest
    container_name: fluxocaixa-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./docker/observability/grafana/provisioning/datasources/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafana-data:/var/lib/grafana
    depends_on:
      - jaeger
      - loki
      - prometheus

volumes:
  loki-data:
  prometheus-data:
  grafana-data:
  rabbitmq-data:
