<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FluxoCaixa.Transactions.Domain\FluxoCaixa.Transactions.Domain.csproj" />
    <ProjectReference Include="..\..\Shared\FluxoCaixa.Shared\FluxoCaixa.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
