@baseUrl = http://localhost:5001

### Criar Transação de Crédito
POST {{baseUrl}}/transactions
Content-Type: application/json

{
  "amount": 150.50,
  "currency": "BRL",
  "transactionType": 1,
  "description": "Venda de produto em loja física"
}

### Criar Transação de Débito
POST {{baseUrl}}/transactions
Content-Type: application/json

{
  "amount": 45.00,
  "currency": "BRL",
  "transactionType": 2,
  "description": "Pagamento de fornecedor de insumos"
}
